[build]
command = "cd exampleSite && hugo --buildDrafts --gc --minify"
publish = "exampleSite/public"

[context.production.environment]
HUGO_VERSION = "0.115.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
