[build]
command = "cd exampleSite && hugo --buildDrafts --minify --gc --themesDir .. --theme ."
publish = "exampleSite/public"

[build.environment]
HUGO_THEME = "hugo-novelist"

[context.production.environment]
HUGO_VERSION = "0.111.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
