[build]
command = "cd exampleSite && hugo --buildDrafts --minify --gc --themesDir .."
publish = "exampleSite/public"

[build.environment]
HUGO_THEME = "hugo-novelist"

[context.production.environment]
HUGO_VERSION = "0.115.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
