baseurl: "https://example.com/"
languageCode: "en-US"
title: "Mary Sue"
theme: novelist
themesDir: "../.."
canonifyurls: true

googleAnalytics: ""
disqusShortname: ""
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
disableHugoGeneratorInject: true
pluralizeListTitles: false
pygmentsCodeFences: false
pygmentsUseClasses: false
minify: false
paginate: 9999
disableKinds:
  - section
  - categories
  - tags

params:
  description: "Since 1973"
  dateFormat: "2006-02-01"
  showSummary: false

permalinks:
  writing: /:year/:month/:day/:slug/

frontmatter:
  author: Example
  github: "https://github.com/loikein"
  facebook: "https://facebook.com/example"
  og_image: 
  sitename: 
  twitter: ""

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed

related:
  includeNewer: true
  threshold: 85
  toLower: false
  indices:
    - name: tags
      weight: 80
    - name: keywords
      weight: 40
    - name: date
      weight: 10
