baseurl: "https://hugo-novelist.netlify.app/"
languageCode: "en-US"
title: "Mary Sue"
# uncomment when you use this theme for production:
# theme: hugo-novelist
# building locally:
# hugo serve --buildDrafts --disableFastRender --themesDir .. --theme .
canonifyurls: true

googleAnalytics: ""
disqusShortname: ""
footnotereturnlinkcontents: "↩"
pluralizeListTitles: false
pygmentsCodeFences: false
pygmentsUseClasses: false
paginate: 9999
# disableKinds:
#   - section
#   - categories
#   - tags

params:
  description: "Since 1973"
  dateFormat: "2006-01-02"
  enableRatings: true
  # Glyph used for <hr>
  # Some suggestions: section sign ("§"), asterism ("⁂"), pilcrow ("❡"), fleuron ("❧")
  # If you want to use Unicode Characters, type double slash like this: "\\12199"
  hrGlyph: "⁂"
  lowVisionSymbols: false
  showSummary: false

taxonomies:
  tag: tags
  fandom: fandoms
  character: characters

markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
  page:
    writing: /:section/:year-:month-:day-:slug/
  section:
    writing: /:section/:year-:month-:day-:slug/

frontmatter:
  author: Example
  github: "https://github.com/loikein"
  facebook: "https://facebook.com/example"
  og_image: 
  sitename: 
  twitter: ""

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed

related:
  includeNewer: true
  threshold: 85
  toLower: false
  indices:
    - name: tags
      weight: 80
    - name: keywords
      weight: 40
    - name: date
      weight: 10
