title: "Mary Sue"
baseurl: "https://hugo-novelist.netlify.app/"
# uncomment the following line when you use this theme for production:
# theme: hugo-novelist
canonifyurls: true
languageCode: "en-US"
hasCJKLanguage: true

googleAnalytics: ""
disqusShortname: ""
footnotereturnlinkcontents: "↩"
pluralizeListTitles: false
paginate: 9999

params:
  description: "Since 1973"
  dateFormat: "2006-01-02"
  customCSS: false
  enableRatings: true
  # Glyph used for <hr>
  # Some suggestions: section sign ("§"), asterism ("⁂"), pilcrow ("❡"), fleuron ("❧")
  # If you want to use Unicode Characters, type double slash like this: "\\2756"
  hrGlyph: "❧"
  lowVisionSymbols: false
  showSummary: false

taxonomies:
  tag: tags
  fandom: fandoms
  relationship: relationships
  character: characters

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    lineNos: false
    lineNumbersInTable: true
    style: algol

permalinks:
  page:
    writing: /:sections/:slugorfilename/
  section:
    writing: /:sections/:slugorfilename/

frontmatter:
  author: Example
  github: "https://github.com/example"
  facebook: "https://facebook.com/example"
  og_image: 
  sitename: 
  twitter: ""

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

outputFormats:
  RSS:
    mediatype: application/rss
    baseName: atom
  JSON:
    mediatype: application/json
    baseName: feed

related:
  includeNewer: true
  threshold: 85
  toLower: false
  indices:
    - name: tags
      weight: 80
    - name: keywords
      weight: 40
    - name: date
      weight: 10
